PREFIX=$(HOME)
CC=g++
AR=ar
CFLAGS= -ggdb  -ansi -Wall -O0
LDFLAGS= -L. -lfhew -lfftw3 
INCLUDE=xdma.h xdma_axi4lite_m.h distrib.h LWE.h FHEW.h FFT.h params.h

all: libfhew.a cmd fhewTest

cmd: cmd/gen cmd/enc cmd/nand cmd/dec cmd/gate

install: $(INCLUDE) libfhew.a
	install $(INCLUDE) $(PREFIX)/include
	install libfhew.a $(PREFIX)/lib

uninstall:
	rm $(PREFIX)/lib/libfhew.a
	rm $(PREFIX)/include/{distrib,LWE,FHEW,FFT,params}.h

clean:
	rm *.o libfhew.a fhewTest modTest ksTest fftTest accTest nandTest cmd/gen cmd/enc cmd/dec cmd/nand cmd/gate || echo nothing to clean

libfhew.a: distrib.o FFT.o LWE.o FHEW.o xdma_axi4lite_m.o xdma.o
	$(AR) -q libfhew.a distrib.o FFT.o LWE.o FHEW.o xdma_axi4lite_m.o xdma.o

distrib.o: distrib.cpp distrib.h params.h
	$(CC) $(CFLAGS) -c distrib.cpp

xdma_axi4lite_m.o: xdma_axi4lite_m.h xdma_axi4lite_m.c
	$(CC) $(CFLAGS) -c xdma_axi4lite_m.c

xdma.o: xdma.h xdma.c
	$(CC) $(CFLAGS) -c xdma.c

FFT.o: FFT.h FFT.cpp params.h FHEW.h
	$(CC) $(CFLAGS) -c FFT.cpp
 
LWE.o: LWE.h LWE.cpp FFT.h params.h distrib.h
	$(CC) $(CFLAGS) -c LWE.cpp

FHEW.o: FHEW.h FHEW.cpp FFT.h LWE.h params.h
	$(CC) $(CFLAGS) -c FHEW.cpp

fhewTest: fhewTest.cpp libfhew.a
	$(CC) $(CFLAGS) -o fhewTest fhewTest.cpp $(LDFLAGS)

modTest: modTest.cpp libfhew.a
	$(CC) $(CFLAGS) -o modTest modTest.cpp $(LDFLAGS)

ksTest: ksTest.cpp libfhew.a
	$(CC) $(CFLAGS) -o ksTest ksTest.cpp $(LDFLAGS)

fftTest: fftTest.cpp libfhew.a
	$(CC) $(CFLAGS) -o fftTest fftTest.cpp $(LDFLAGS)

accTest: accTest.cpp libfhew.a
	$(CC) $(CFLAGS) -o accTest accTest.cpp $(LDFLAGS)

nandTest: nandTest.cpp libfhew.a
	$(CC) $(CFLAGS) -o nandTest nandTest.cpp $(LDFLAGS)

common.o: cmd/common.cpp cmd/common.h libfhew.a
	$(CC) $(CFLAGS) -c cmd/common.cpp 

cmd/gen: cmd/gen.cpp common.o libfhew.a
	$(CC) $(CFLAGS) -o cmd/gen cmd/gen.cpp common.o $(LDFLAGS)

cmd/enc: cmd/enc.cpp common.o libfhew.a
	$(CC) $(CFLAGS) -o cmd/enc cmd/enc.cpp common.o $(LDFLAGS)

cmd/nand: cmd/nand.cpp common.o libfhew.a
	$(CC) $(CFLAGS) -o cmd/nand cmd/nand.cpp common.o $(LDFLAGS)

cmd/gate: cmd/gate.cpp common.o libfhew.a
	$(CC) $(CFLAGS) -o cmd/gate cmd/gate.cpp common.o $(LDFLAGS)

cmd/dec: cmd/dec.cpp common.o libfhew.a
	$(CC) $(CFLAGS) -o cmd/dec cmd/dec.cpp common.o $(LDFLAGS)
