# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fangyuhong/dma/alveo_u280/alveo_u280.srcs/sources_1/ip/int_ila_0/int_ila_0.xci
# IP: The module: 'int_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/int_ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_ila_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/int_ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/int_ila_0/int_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/fangyuhong/dma/alveo_u280/alveo_u280.srcs/sources_1/ip/int_ila_0/int_ila_0.xci
# IP: The module: 'int_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/int_ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/int_ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/int_ila_0/int_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
