# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fangyuhong/dma/alveo_u280/alveo_u280.srcs/sources_1/ip/afifo_ddr_burst/afifo_ddr_burst.xci
# IP: The module: 'afifo_ddr_burst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/afifo_ddr_burst/afifo_ddr_burst.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_ddr_burst'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/afifo_ddr_burst/afifo_ddr_burst_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_ddr_burst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/afifo_ddr_burst/afifo_ddr_burst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_ddr_burst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/fangyuhong/dma/alveo_u280/alveo_u280.srcs/sources_1/ip/afifo_ddr_burst/afifo_ddr_burst.xci
# IP: The module: 'afifo_ddr_burst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/afifo_ddr_burst/afifo_ddr_burst.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_ddr_burst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/afifo_ddr_burst/afifo_ddr_burst_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_ddr_burst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fangyuhong/dma/alveo_u280/alveo_u280.gen/sources_1/ip/afifo_ddr_burst/afifo_ddr_burst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_ddr_burst'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
